services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    restart: unless-stopped
  
  meteorolog:
    build: ./meteorolog  # Your Rust app Dockerfile is in ./meteorolog
    container_name: meteorolog
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_DATABASE=meteo_db
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true
    restart: unless-stopped

  weatherman:
    build: ./weatherman
    container_name: weatherman
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_DATABASE=meteo_db
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
